torchrun  --nproc_per_node=2 --master_port=1212 train.py \
    --model_name_or_path models/darwin-7b_v2 \
    --data_path datasets/drug_discovery/tabular/BROAD_REPURPOSING_DRUGS.json \
    --bf16 True \
    --output_dir models/darwin-7b_v2_finetuned \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 False
